language: go

go:
    - 1.x

services:
    - mysql

before_script:
    - ./sql/setup_db.sh -t
    - ./sql/setup_blob_dirs.sh

notifications:
    email:
        recipients:
            - js@ojuslabs.com
        on_success: change
        on_failure: always
